name: C++ CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  actions: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make
        
    - name: Build Basic Linked List
      run: |
        cd basic_linked_list
        make clean
        make
        
    - name: Run Automated Tests
      run: |
        cd basic_linked_list
        chmod +x test.sh
        ./test.sh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpp-binaries-${{ github.sha }}
        path: |
          basic_linked_list/linkedlist
          basic_linked_list/README.md
        retention-days: 30

  build-artifacts:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make
        
    - name: Build for Release
      run: |
        cd basic_linked_list
        make clean
        make
        
    - name: Package Release
      run: |
        mkdir -p release
        cp basic_linked_list/linkedlist release/
        cp basic_linked_list/README.md release/
        cp basic_linked_list/LinkedList.h release/
        cp basic_linked_list/main.cpp release/
        cp basic_linked_list/Makefile release/
        cp basic_linked_list/test.sh release/
        tar -czf cpp-programming-release.tar.gz release/
        
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-package-${{ github.sha }}
        path: |
          cpp-programming-release.tar.gz
          release/
        retention-days: 90
